[env]

[db]
    #数据库目标
    dsn = "root:123456@tcp(127.0.0.1:3306)/customClothing?parseTime=True&loc=Local"
    #最大空闲连接数
    maxIdle = 10
    #最大连接数
    maxOpen = 10
    #日志级别，Silent Err Warn Info，silent不输入任何日志
    level = "Info"

[token]
    #超时时间 默认2小时（单位：秒）
    timeout = 7200
    #缓存key
    cacheKey = "token:"
    #Token分隔符，默认：-
    tokenDelimiter = "-"
    #token请求头存储字段
    headerKey = "Authorization"
    #token数据加密key
    encryptKey = "eb86b17dfaaf4f0db8f74e6a00647a82"
    #是否支持多端登录，默认false
    multiLogin = false

[redis]
    #redis地址
    addr = "127.0.0.1:6379"
    #redis数据库编号0-15取值
    db = 0
    #连接池配额
    poolSize = 10
    #最小空闲连接配额
    idleConns = 10
