// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm": {
            "post": {
                "description": "甲方确认订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "确认订单",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.ConfirmOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.ConfirmOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order": {
            "put": {
                "description": "甲方取消订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "取消订单",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.CancelOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.CancelOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            },
            "post": {
                "description": "管理员删除需求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "删除需求",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.DeleteOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.DeleteOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/all": {
            "get": {
                "description": "查询自己发布的or接手的需求订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "获取所有需求",
                "parameters": [
                    {
                        "type": "number",
                        "description": "用户uuid",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "用户角色code: 0 = 管理员，1 = 普通用户，2 = 设计师，3 = 版型师",
                        "name": "roleCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "订单状态: 1 = 待接单, 2 = 已过期, 3 = 进行中, 4 = 已完成, 5 = 已取消",
                        "name": "status",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.ListOrdersResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/cost": {
            "post": {
                "description": "修改订单费用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "修改订单费用",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UpdateCostReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UpdateCostResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/designArtwork": {
            "post": {
                "description": "乙方上传设计图稿",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "上传设计图稿",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadDesignArtworkReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadDesignArtworkResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/detail": {
            "get": {
                "description": "查询订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "查询订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单uuid",
                        "name": "orderId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.GetOrderDetailResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/patternArtwork": {
            "post": {
                "description": "乙方上传版型图稿",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "上传版型图稿",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadPatternArtworkReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadPatternArtworkResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/patternMakingProcess": {
            "post": {
                "description": "乙方上传版型制作工艺",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "上传版型制作工艺",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadPatternMakingProcessReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadPatternMakingProcessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/pickupOrder": {
            "post": {
                "description": "乙方接单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "接单",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.PickupOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.PickupOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/reporter": {
            "post": {
                "description": "举报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "举报",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.ReportOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.ReportOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/sampleImage": {
            "post": {
                "description": "乙方上传样品成衣图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "上传样品成衣图",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadSampleImageReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadSampleImageResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/showVideo": {
            "post": {
                "description": "乙方上传模特展示视频",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "上传模特展示视频",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadShowVideoReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.UploadShowVideoResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/single": {
            "get": {
                "description": "查询自己发布的or接手的需求订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "获取单个需求",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单uuid",
                        "name": "orderId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.GetOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/order/sum": {
            "get": {
                "description": "首页中，查询总交易订单次数+总交易金额",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "查询总交易订单次数+总交易金额",
                "parameters": [
                    {
                        "type": "string",
                        "description": "无参数",
                        "name": "None",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.GetOrderSumResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            },
            "post": {
                "description": "甲方发布需求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order模块"
                ],
                "summary": "发布需求",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderService.PublishOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderService.PublishOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.RegisterUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.RegisterUserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user/authcode": {
            "get": {
                "description": "获取验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "无参数",
                        "name": "None",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.RegisterUserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user/kyc": {
            "post": {
                "description": "Kyc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "Kyc",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.KycReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.KycResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user/margin": {
            "get": {
                "description": "查询保证金",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "查询保证金",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uuid",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.GetMarginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            },
            "put": {
                "description": "乙方保证金提现",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "保证金提现",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.WithdrawMarginReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.WithdrawMarginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            },
            "post": {
                "description": "乙方缴纳保证金",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "缴纳保证金",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.PayMarginReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.PayMarginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员扣除保证金",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "扣除保证金",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.DeductMarginReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.DeductMarginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        },
        "/user/status": {
            "put": {
                "description": "管理员拉黑、解除拉黑用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user模块"
                ],
                "summary": "拉黑、解除拉黑用户",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.UpdateUserStatusReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userService.UpdateUserStatusResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "orderService.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "市",
                    "type": "string"
                },
                "contact": {
                    "description": "联系人",
                    "type": "string"
                },
                "detail": {
                    "description": "详细地址",
                    "type": "string"
                },
                "district": {
                    "description": "区",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "province": {
                    "description": "省",
                    "type": "string"
                }
            }
        },
        "orderService.Bottom": {
            "type": "object",
            "properties": {
                "headCircumference": {
                    "description": "净头围[单位cm]",
                    "type": "number"
                },
                "hipCircumference": {
                    "description": "净臀围[单位cm]",
                    "type": "number"
                },
                "length": {
                    "description": "裤长[单位cm]",
                    "type": "number"
                },
                "thighCircumference": {
                    "description": "净大腿围[单位cm]",
                    "type": "number"
                },
                "waistline": {
                    "description": "净腰围[单位cm]",
                    "type": "number"
                }
            }
        },
        "orderService.CancelOrderReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.CancelOrderResp": {
            "type": "object"
        },
        "orderService.Coat": {
            "type": "object",
            "properties": {
                "armCircumference": {
                    "description": "手臂围[单位cm]",
                    "type": "number"
                },
                "bust": {
                    "description": "净胸围[单位cm]",
                    "type": "number"
                },
                "clothLength": {
                    "description": "衣长[单位cm]",
                    "type": "number"
                },
                "shoulderWidth": {
                    "description": "肩宽[单位cm]",
                    "type": "number"
                },
                "sleeveLength": {
                    "description": "袖长[单位cm]",
                    "type": "number"
                }
            }
        },
        "orderService.ConfirmOrderReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.ConfirmOrderResp": {
            "type": "object"
        },
        "orderService.ConsumptionPositioning": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄层：18-24，24-28，26-30，33-38等",
                    "type": "integer"
                },
                "earn": {
                    "description": "收入范围：5000-8000，7000-9000，10000-11000等",
                    "type": "integer"
                },
                "profession": {
                    "description": "职业：自填",
                    "type": "string"
                }
            }
        },
        "orderService.DeleteOrderReq": {
            "type": "object",
            "properties": {
                "adminId": {
                    "description": "管理员uuid",
                    "type": "string"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.DeleteOrderResp": {
            "type": "object"
        },
        "orderService.GetOrderDetailResp": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/orderService.OrderDetail"
                }
            }
        },
        "orderService.GetOrderResp": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/orderService.Order"
                }
            }
        },
        "orderService.GetOrderSumResp": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "总交易金额",
                    "type": "number"
                },
                "sum": {
                    "description": "总交易次数",
                    "type": "integer"
                }
            }
        },
        "orderService.ListOrdersResp": {
            "type": "object",
            "properties": {
                "orders": {
                    "description": "订单列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderService.Order"
                    }
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "orderService.Order": {
            "type": "object",
            "properties": {
                "cost": {
                    "description": "费用",
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "designArtwork": {
                    "description": "设计图稿地址",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "partA": {
                    "description": "甲方uuid",
                    "type": "string"
                },
                "partB": {
                    "description": "乙方uuid",
                    "type": "string"
                },
                "patternArtwork": {
                    "description": "版型图稿地址",
                    "type": "string"
                },
                "patternMakingProcess": {
                    "description": "版型制作工艺",
                    "type": "string"
                },
                "sampleImage": {
                    "description": "样品成衣图地址",
                    "type": "string"
                },
                "showVideo": {
                    "description": "模特展示视频地址",
                    "type": "string"
                },
                "status": {
                    "description": "订单状态",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "orderService.OrderDetail": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "收货地址",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.Address"
                        }
                    ]
                },
                "confirmSteps": {
                    "description": "步骤确认",
                    "type": "string"
                },
                "consumptionPositioning": {
                    "description": "消费定位",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.ConsumptionPositioning"
                        }
                    ]
                },
                "cost": {
                    "description": "费用",
                    "type": "number"
                },
                "deadLine": {
                    "description": "截止时间",
                    "type": "string"
                },
                "description": {
                    "description": "需求大致介绍",
                    "type": "string"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "part": {
                    "description": "制作类别",
                    "type": "string"
                },
                "patternCost": {
                    "description": "版型费用",
                    "type": "number"
                },
                "patternRequest": {
                    "description": "版型工艺制作要求",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.PatternRequest"
                        }
                    ]
                },
                "productionTime": {
                    "description": "制作天数要求",
                    "type": "integer"
                },
                "provideFabric": {
                    "description": "是否需要提供面料",
                    "type": "boolean"
                },
                "referenceSize": {
                    "description": "参考尺寸",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.ReferenceSize"
                        }
                    ]
                },
                "sampleCost": {
                    "description": "成衣样衣费用",
                    "type": "number"
                },
                "style": {
                    "description": "风格描述",
                    "type": "string"
                },
                "wearingOccasion": {
                    "description": "穿着场合",
                    "type": "string"
                }
            }
        },
        "orderService.PatternRequest": {
            "type": "object",
            "properties": {
                "contour": {
                    "description": "轮廓设计：A H X Y T V O；",
                    "type": "string"
                },
                "function": {
                    "description": "功能要求：自填；",
                    "type": "string"
                },
                "localDesign": {
                    "description": "局部设计：绣花、印花、领口、袖口、门襟；",
                    "type": "integer"
                },
                "looseness": {
                    "description": "宽松度：紧身、合体、宽松；",
                    "type": "integer"
                },
                "patternStructure": {
                    "description": "版型结构：立体或者平面；",
                    "type": "integer"
                }
            }
        },
        "orderService.PickupOrderReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "userId": {
                    "description": "乙方uuid",
                    "type": "string"
                }
            }
        },
        "orderService.PickupOrderResp": {
            "type": "object"
        },
        "orderService.PublishOrderReq": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "收货地址",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.Address"
                        }
                    ]
                },
                "confirmSteps": {
                    "description": "步骤确认",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "consumptionPositioning": {
                    "description": "消费定位",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.ConsumptionPositioning"
                        }
                    ]
                },
                "cost": {
                    "description": "费用",
                    "type": "number"
                },
                "customStyle": {
                    "description": "自定义风格描述",
                    "type": "string"
                },
                "deadLine": {
                    "description": "截止时间",
                    "type": "string"
                },
                "description": {
                    "description": "需求大致介绍",
                    "type": "string"
                },
                "part": {
                    "description": "制作类别",
                    "type": "integer"
                },
                "patternCost": {
                    "description": "版型费用",
                    "type": "number"
                },
                "patternRequest": {
                    "description": "版型工艺制作要求",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.PatternRequest"
                        }
                    ]
                },
                "productionTime": {
                    "description": "制作天数要求",
                    "type": "integer"
                },
                "provideFabric": {
                    "description": "是否需要提供面料",
                    "type": "boolean"
                },
                "referenceSize": {
                    "description": "参考尺寸",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.ReferenceSize"
                        }
                    ]
                },
                "sampleCost": {
                    "description": "成衣样衣费用",
                    "type": "number"
                },
                "style": {
                    "description": "风格描述",
                    "type": "integer"
                },
                "userId": {
                    "description": "甲方uuid",
                    "type": "string"
                },
                "wearingOccasion": {
                    "description": "穿着场合",
                    "type": "integer"
                }
            }
        },
        "orderService.PublishOrderResp": {
            "type": "object"
        },
        "orderService.ReferenceSize": {
            "type": "object",
            "properties": {
                "bottom": {
                    "description": "下装",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.Bottom"
                        }
                    ]
                },
                "coat": {
                    "description": "上衣",
                    "allOf": [
                        {
                            "$ref": "#/definitions/orderService.Coat"
                        }
                    ]
                },
                "height": {
                    "description": "身高",
                    "type": "integer"
                },
                "weight": {
                    "description": "体重",
                    "type": "integer"
                }
            }
        },
        "orderService.ReportOrderReq": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "举报描述",
                    "type": "string"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "reportedPerson": {
                    "description": "被举报人uuid",
                    "type": "string"
                },
                "whistleblower": {
                    "description": "举报人uuid",
                    "type": "string"
                }
            }
        },
        "orderService.ReportOrderResp": {
            "type": "object"
        },
        "orderService.UpdateCostReq": {
            "type": "object",
            "properties": {
                "cost": {
                    "description": "费用",
                    "type": "number"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.UpdateCostResp": {
            "type": "object"
        },
        "orderService.UploadDesignArtworkReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.UploadDesignArtworkResp": {
            "type": "object"
        },
        "orderService.UploadPatternArtworkReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.UploadPatternArtworkResp": {
            "type": "object"
        },
        "orderService.UploadPatternMakingProcessReq": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "工艺内容",
                    "type": "string"
                },
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                }
            }
        },
        "orderService.UploadPatternMakingProcessResp": {
            "type": "object"
        },
        "orderService.UploadSampleImageReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "url": {
                    "description": "成衣图url地址",
                    "type": "string"
                }
            }
        },
        "orderService.UploadSampleImageResp": {
            "type": "object"
        },
        "orderService.UploadShowVideoReq": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单uuid",
                    "type": "string"
                },
                "url": {
                    "description": "视频url地址",
                    "type": "string"
                }
            }
        },
        "orderService.UploadShowVideoResp": {
            "type": "object"
        },
        "response.response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "userService.DeductMarginReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "扣除金额",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.DeductMarginResp": {
            "type": "object"
        },
        "userService.GetMarginResp": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "保证金数量",
                    "type": "integer"
                }
            }
        },
        "userService.KycReq": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "roleCode": {
                    "description": "申请成为的角色",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.KycResp": {
            "type": "object"
        },
        "userService.LoginReq": {
            "type": "object",
            "properties": {
                "authCode": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "userService.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/userService.User"
                }
            }
        },
        "userService.PayMarginReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "缴纳金额",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.PayMarginResp": {
            "type": "object"
        },
        "userService.RegisterUserReq": {
            "type": "object",
            "properties": {
                "displayName": {
                    "description": "昵称，长度6-20",
                    "type": "string"
                },
                "password": {
                    "description": "密码，长度6-20",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "userService.RegisterUserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "userService.Role": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "角色代码",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "角色名",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "userService.UpdateUserStatusReq": {
            "type": "object",
            "properties": {
                "adminId": {
                    "description": "管理员uuid",
                    "type": "string"
                },
                "status": {
                    "description": "状态:1=拉黑，2=解除拉黑",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.UpdateUserStatusResp": {
            "type": "object"
        },
        "userService.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像图片地址",
                    "type": "string"
                },
                "ban": {
                    "description": "用户是否被拉黑",
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "displayName": {
                    "description": "昵称",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "margin": {
                    "description": "保证金",
                    "type": "integer"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "role": {
                    "description": "角色",
                    "allOf": [
                        {
                            "$ref": "#/definitions/userService.Role"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.WithdrawMarginReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "提现金额",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "userService.WithdrawMarginResp": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
